Edit documentation
GDWR/classy-config pull request #41
Opened 2022-05-06 02:00 UTC by minalike

This PR is a proofreading and light editing of the documentation of ClassyConfig.

Pages reviewed:

- [x] Getting Started
- [x] Load Your Config
- [x] Using Multiple Configs
- [ ] Conflicting Configs
- [ ] Custom Loaders
- [ ] Reference

Notes:
- Double quotes were more prevalent in the examples and so single quotes were converted to match
- Some examples are documented on the repo as well and should also be updated once satisfied with the changes (e.g.: [using multiple configs](https://github.com/GDWR/classy-config/tree/main/examples/multiple_configs))

Suggestions:
- It would be nice to capitalize the word "documentation" in the page title and banner
- Perhaps a link to the source code repository in the footer

2022-08-12 08:44 UTC, GDWR commented
@minalike Is it okay for me to review your current changes and look for them to be merged into `main`? The additional pages you have listed you would review can be done in another PR.

2022-08-12 20:56 UTC, minalike commented
Yes please go ahead.

2022-09-12 12:44 UTC, GDWR requested changes
One change, after that I will merge into main. Cheers.

2022-09-12 12:44 UTC, GDWR commented on docs/source/guides/custom-loaders.rst
> +    print(f"name: {ConfigValue("name", str)}")
The internal single quote was used on purpose, it is required to use the alternative quote for strings inside f-strings.

2022-09-12 16:51 UTC, merged